version: '3.4'

services:
  grafana-agent:
    build: grafana-agent/target
    network_mode: host
    env_file:
      - grafana-agent/.env
  ipfs:
    image: ipfs/kubo:v0.14.0
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - IPFS_PROFILE=server
      - OTEL_TRACES_SAMPLER=traceidratio
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_TRACES_SAMPLER_ARG=0.1
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
  